spring:
  security:
    oauth2:
      client:
        registration:
          twitch:
            clientId: "${twitch.api.clientId}"
            clientSecret: "${twitch.api.secret}"
            scope: ["user:read:email","openid","chat:read","clips:edit"]
        provider:
          twitch:
            issuer-uri: https://id.twitch.tv/oauth2
