spring:
  security:
    oauth2:
      client:
        registration:
          twitch:
            clientId: 54uoe3en5xvqlc0z0mdw3ghuucmvpk
            clientSecret: qxn7myepvb1qy4dl4wqxmvdlnhozdg
            scope: ["user:read:email","openid","chat:read"]
        provider:
          twitch:
            issuer-uri: https://id.twitch.tv/oauth2
